version: "3"

services:
    npm:
        image: node
        user: node
        working_dir: /home/node
        entrypoint: npm
        volumes:
            - .:/home/node

    node:
        image: node
        user: node
        working_dir: /home/node
        volumes:
            - .:/home/node
